export const boxMessage: string;
export const center: string;
export const flexList: string;
export const hideInPlace: string;
export const icon: string;
export const jump: string;
export const layoutBox: string;
export const red: string;
export const title: string;
