export const center: string;
export const flexList: string;
export const highlight: string;
export const layoutBox: string;
export const lbIcon: string;
export const lbText: string;
export const linkBox: string;
export const small: string;
export const title: string;
